import type { Metadata } from 'next'
import { Cairo, JetBrains_Mono } from 'next/font/google'
import { ThemeProvider } from '../components/theme-provider'
import { Toaster } from '../components/ui/sonner'
import { EdgeStoreProvider } from '../lib/edgestore'
import './globals.css'

const cairoSans = Cairo({
  variable: '--font-sans',
  subsets: ['arabic', 'latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
})

const jetBrainsMono = JetBrains_Mono({
  variable: '--font-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ar' dir='rtl' suppressHydrationWarning>
      <body className={`${cairoSans.variable} ${jetBrainsMono.variable} antialiased`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <EdgeStoreProvider>{children}</EdgeStoreProvider>

          <Toaster position='top-center' richColors />
        </ThemeProvider>
      </body>
    </html>
  )
}
